default: &default
  adapter: postgresql
  encoding: unicode
  
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
production:
  primary: &primary_production
    <<: *default
    database: backend_production
    username: backend
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_production_cable
    migrations_paths: db/cable_migrate
